#!/usr/bin/python
# -*- coding: utf-8 -*-

gpio=3

from gpiozero import Button
from signal import pause
from subprocess import check_call
from time import time

pushed_at = None

def button_pushed():
    global pushed_at
    pushed_at = time()

def button_released():
    global pushed_at
    if pushed_at is None:
        return
    held_for = now - pushed_at
    if (held_for > 2.0):
        check_call(['/sbin/poweroff'])
    elif (held_for > 0.1):
        check_call(['/sbin/sway-toggle-fullscreen'])
    pushed_at = None

button=Button(gpio)
button.when_pressed = button_pushed
button.when_released = button_released

pause() # wait forever

